.TH RUNES 1 "v1.0" 
.SH NAME
runes \- mouse gesture utility
.SH SYNOPSIS
.B runes 
[\fI0|1\fR] [\fIrunes collection filename\fR]
.SH DESCRIPTION
.B runes 
The runes is an application that lets a user draw, store and recognize rune 
patterns, made by one line.
.IP \fBMode 0\fR
Draw and save patterns to rune collection.
.IP \fBMode 1\fR
Draw and recognize gesture from rune collection.
.SH FILES
.TP
\fI~/.config/runes\fR
The default file used to save and load patterns.
